source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Pixpie-iOS_Example', :exclusive => true do
  pod "Pixpie-iOS", :path => "../"
end

target 'Pixpie-iOS_Tests', :exclusive => true do
  pod "Pixpie-iOS", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
