source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/PixpieCo/PixpieCocoapods.git'
use_frameworks!

target 'InspiringPhotos' do
  pod 'Pixpie', :path => "../"
  pod 'PXStatusView'
  # pod 'Crashlytics'
  pod 'InAppSettingsKit'
  pod 'HockeySDK', '~> 3.8.5'
end

target 'Pixpie-iOS_Tests' do
  pod 'Pixpie', :path => "../"
  pod 'Specta'
  pod 'Expecta'
end
