# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache:
 - bundler
 - cocoapods

osx_image: xcode8.1sneakpeek

before_install:
 - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
 - pod install --project-directory=Example

install:
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
 - set -o pipefail && xcodebuild test -workspace Example/Pixpie-iOS.xcworkspace -scheme InspiringPhotos -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - pod lib lint --quick --private
