source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/PixpieCo/PixpieCocoapods.git'
#use_frameworks!
platform :ios, '8.0'

target 'Pixpie' do
  pod 'AFNetworking', "~> 3.0"
  pod 'WebP'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = 'arm64 armv7 armv7s i386 x86_64'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'

            if config.name.include?("Debug")
                config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
                config.build_settings['COPY_PHASE_STRIP'] = 'NO'
                config.build_settings['STRIP_STYLE'] = 'debugging'
                config.build_settings['GCC_SYMBOLS_PRIVATE_EXTERN'] = 'NO'
                config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
            else
                config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
                config.build_settings['COPY_PHASE_STRIP'] = 'YES'
                config.build_settings['STRIP_STYLE'] = 'non-global'
                config.build_settings['GCC_SYMBOLS_PRIVATE_EXTERN'] = 'YES'
                config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'
            end
        end
    end
end

