source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/PixpieCo/PixpieCocoapods.git'
#use_frameworks!

target 'Pixpie' do
  pod 'AFNetworking', "~> 3.0"
  pod 'WebP'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = 'arm64 armv7 armv7s i386 x86_64'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

